server:
  # 端口
  port: 80
  servlet:
    # 项目路径
    context-path: /page
spring:
  application:
    # 项目名
    name: xiao-navigation
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接
    url: jdbc:mysql://localhost:3307/xiao_navigation?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
    # 数据库名
    username: root
    # 数据库密码
    password: 123456
  mvc:
    pathmatch:
      # 兼容knife4j
      matching-strategy: ant_path_matcher
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 数据库下划线自动转驼峰标示关闭(为true，就简单粗暴的把下划线干掉了)
  mapper-locations: classpath*:mapper/*.xml # 读取mapper包下映射
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: cn.coisini.navigation.model.pojos

# 分布式ID设置
# 机器ID
workId: 0
# 数据中心ID
datacenterId: 0

# 启动类打印接口地址
ipaddr: http://localhost

